//------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a tool.
//  For the template that generated the code please refer to:
//  .\BlazorWasmBlog.SquidexCms\Configuration\SquidexCmsSettings.tt
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using BlazorWasmBlog.Core.Domain.Configuration;
using System.Diagnostics.CodeAnalysis;

namespace BlazorWasmBlog.SquidexCms.Configuration
{
    [ExcludeFromCodeCoverage]
    public class SquidexCmsConfiguration : IConfigurationSettings
    {
        /// <summary>
        /// Configuration.Development.json
        /// </summary>
        public static string Configuration_Development
        {
            get
            {
                return @"{
  ""SquidexCmsSettings"": {
    ""Url"": ""https://cloud.squidex.io"",
    ""AppName"": ""todo"",
    ""ClientId"": ""todo:default"",
    ""ClientSecret"": ""todo""
  }
}";
            }
        }
        /// <summary>
        /// Configuration.json
        /// </summary>
        public static string Configuration
        {
            get
            {
                return @"{
  ""SquidexCmsSettings"": {
    ""Url"": ""https://cloud.squidex.io"",
    ""AppName"": ""todo"",
    ""ClientId"": ""todo:default"",
    ""ClientSecret"": ""todo""
  }
}";
            }
        }
    }
}