//------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a tool.
//  For the template that generated the code please refer to:
//  .\BlazorWasmBlog.Blazor\Configuration\SquidexCmsConfiguration.tt
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using BlazorWasmBlog.Core.Infrastructure.Configuration;
using System.Diagnostics.CodeAnalysis;

namespace BlazorWasmBlog.Blazor.Configuration
{
    [ExcludeFromCodeCoverage]
    public class SquidexCmsConfigurationSettings : IConfigurationSettings
    {
        /// <summary>
        /// SquidexCmsConfiguration.Development.json
        /// </summary>
        public const string SquidexCmsConfiguration_Development = 
            @"{
  ""SquidexCmsSettings"": {
    ""Url"": ""https://cloud.squidex.io"",
    ""AppName"": ""todo.dev"",
    ""ClientId"": ""todo.dev:default"",
    ""ClientSecret"": ""todo.dev""
  }
}";
        /// <summary>
        /// SquidexCmsConfiguration.json
        /// </summary>
        public const string SquidexCmsConfiguration = 
            @"{
  ""SquidexCmsSettings"": {
    ""Url"": ""https://cloud.squidex.io"",
    ""AppName"": ""blazorwasmblog"",
    ""ClientId"": ""blazorwasmblog:default"",
    ""ClientSecret"": ""YOUR-SECRET-HERE""
  }
}";
        
        public string GetSettings(string environmentName)
        {
            if (string.IsNullOrEmpty(environmentName))
            {
                environmentName= "Default";
            }

            if (environmentName.Equals("Development", System.StringComparison.OrdinalIgnoreCase))
            {
                return SquidexCmsConfiguration_Development;
            }

            if (environmentName.Equals("Default", System.StringComparison.OrdinalIgnoreCase))
            {
                return SquidexCmsConfiguration;
            }

            return string.Empty;
        }
    }
}