//------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a tool.
//  For the template that generated the code please refer to:
//  .\BlazorWasmBlog.Blazor\Configuration\SquidexCmsConfiguration.tt
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using BlazorWasmBlog.Core.Infrastructure.Configuration;
using System.Diagnostics.CodeAnalysis;

namespace BlazorWasmBlog.Blazor.Configuration
{
    [ExcludeFromCodeCoverage]
    public class SquidexCmsConfigurationSettings : IConfigurationSettings
    {
        /// <summary>
        /// SquidexCmsConfiguration.Development.json
        /// </summary>
        public static string SquidexCmsConfiguration_Development
        {
            get
            {
                return @"{
  ""SquidexCmsSettings"": {
    ""Url"": ""https://cloud.squidex.io"",
    ""AppName"": ""todo.dev"",
    ""ClientId"": ""todo.dev:default"",
    ""ClientSecret"": ""todo.dev""
  }
}";
            }
        }
        /// <summary>
        /// SquidexCmsConfiguration.json
        /// </summary>
        public static string SquidexCmsConfiguration
        {
            get
            {
                return @"{
  ""SquidexCmsSettings"": {
    ""Url"": ""https://cloud.squidex.io"",
    ""AppName"": ""todo"",
    ""ClientId"": ""todo:default"",
    ""ClientSecret"": ""todo""
  }
}";
            }
        }
        
        public string GetSettings()
        {
            var settings = SquidexCmsConfiguration_Development;
            return settings;
        }

        public string GetDevelopmentSettings()
        {
            var settings = SquidexCmsConfiguration;
            return settings;
        }

    }
}